In [5]:
#1. Importa el paquete NUMPY bajo el nombre np.

import numpy as np

In [7]:
#2. Imprime la versión de NUMPY y la configuración.

# Imprimir la versió de numpy
print("Versió de numpy:", np.__version__)

# Imprimir la configuració
print("Configuració de numpy:")
np.show_config()

Versió de numpy: 1.26.4
Configuració de numpy:
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: d:/Users/estev/anaconda3/Library/include
    lib directory: d:/Users/estev/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1583119523984
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    famil

In [7]:
#3 i #4. Genera un array tridimensional de 2x3x5 con valores aleatorios. Asigna el array a la variable "a"
# Desafío: hay al menos tres maneras fáciles que usan numpy para generar arrays aleatorios. ¿Cuántas formas puedes encontrar?

# Generar un array tridimensional de 2x3x5 amb valors naturals aleatoris entre 0 i 10 (trio naturals aleatoris entre 0 i 10 per facilitar-me la vida després).
a = np.random.randint(0, 10, (2, 3, 5))
print(a)

# Desafiament:

# a) np.random.rand ens genera nombres aleatoris a l'inteval [0,1]
# b) np.random.randn ens genera nombres aleatoris d'una distribució N(0,1)
# c) np.random.dandint: genera nombresn enters aleatoris dintre d'un rang especificat (que és l'opció que he triat jo).

[[[0 2 1 0 6]
  [0 8 6 3 4]
  [1 6 8 7 0]]

 [[5 7 4 5 1]
  [0 7 4 0 3]
  [3 2 4 8 9]]]


In [17]:
#5. i #6 Crea un array tridimensional de 5x2x3 con todos los valores igual a 1.
#Asigna el array a la variable "b"

b = np.ones((5, 2, 3), dtype=int)
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


In [19]:
#7. ¿Tienen a y b el mismo tamaño? ¿Cómo lo demuestras en código Python?

# No. 

print(f"La dimensió de 'a' és: {a.shape}")
print(f"La dimensió de 'b' és: {b.shape}")
if a.shape == b.shape :
    print("Les dimensions coincideixen, a i b tenen la mateixa mida")
else :
    print("Les dimensions no coincideixen, a i b no tenen la mateixa mida")

La dimensió de 'a' és: (2, 3, 5)
La dimensió de 'b' és: (5, 2, 3)
Les dimensions no coincideixen, a i b no tenen la mateixa mida


In [ ]:
#8. ¿Es posible sumar a y b? ¿Por qué sí o por qué no?

No, no es posible sumar a y b porque sus dimensiones no coinciden.

In [21]:
#9. Transpone b para que tenga la misma estructura que a (es decir, se convierta en un array de 2x3x5). Asigna el array transpuesto a la variable "c".

# Fem bT per tal que tingui la forma (2, 3, 5)

c = np.transpose(b, (1, 2, 0))

print(f"Forma original de b: {b.shape}")
print(f"Forma trasposada de b (c): {c.shape}")

Forma original de b: (5, 2, 3)
Forma trasposada de b (c): (2, 3, 5)


In [23]:
#10. Intenta sumar a y c. Ahora debería funcionar. Asigna la suma a la variable "d". Pero, ¿por qué funciona ahora?

# Sumem a i c :
d = a + c

print(f"Suma de a i c (d):\n{d}")


Suma de a i c (d):
[[[ 1  3  2  1  7]
  [ 1  9  7  4  5]
  [ 2  7  9  8  1]]

 [[ 6  8  5  6  2]
  [ 1  8  5  1  4]
  [ 4  3  5  9 10]]]


In [ ]:
# Ahora funciona porque la suma en Python está definida como la suma punto a punto. Al tener los arrays el mismo tamaño y los elementos ser del mismo tipo
# (enteros, en este caso) la operación que intentamos hacer entra dentro de las hipótesis definitorias de la suma.

In [29]:
#11. Imprime a y d. ¿Notas la diferencia y la relación entre los dos arrays en términos de los valores? Explica.

print(f"a:\n{a}")
print(f"d:\n{d}")

a:
[[[0 2 1 0 6]
  [0 8 6 3 4]
  [1 6 8 7 0]]

 [[5 7 4 5 1]
  [0 7 4 0 3]
  [3 2 4 8 9]]]
d:
[[[ 1  3  2  1  7]
  [ 1  9  7  4  5]
  [ 2  7  9  8  1]]

 [[ 6  8  5  6  2]
  [ 1  8  5  1  4]
  [ 4  3  5  9 10]]]


In [ ]:
# Podemos observar que los valores de d se obtienen a partir de los de a sumándoles una unidad, que es justo el contenido de b.

In [33]:
#12. Multiplica a y c. Asigna el resultado a e.

# Producte de a i c.

e = a * c

print(f"a:\n{a}")
print(f"\nc:\n{c}")
print(f"\nProducte de a i c (e):\n{e}")

a:
[[[0 2 1 0 6]
  [0 8 6 3 4]
  [1 6 8 7 0]]

 [[5 7 4 5 1]
  [0 7 4 0 3]
  [3 2 4 8 9]]]

c:
[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]

Producte de a i c (e):
[[[0 2 1 0 6]
  [0 8 6 3 4]
  [1 6 8 7 0]]

 [[5 7 4 5 1]
  [0 7 4 0 3]
  [3 2 4 8 9]]]


In [43]:
#13. ¿Es e igual a a? ¿Por qué sí o por qué no?

if e.all() == a.all() :
    print("L'array e és igual a l'array a")
else :
    print("L'array a i l'arrray c són diferents")


L'array e és igual a l'array a


In [ ]:
# El producte, com la suma, també està definit element a element. Com que en aquest cas estem multiplicant per l'element neutre del producte
# és d'esperar que l'array original i l'obtingut com a resultat del producte coincideixin.

In [45]:
#14. Identifica los valores máximos, mínimos y medios en d. Asigna esos valores a las variables "d_max", "d_min" y "d_mean"

# Trobem els valors màxim, mínim i mitjà de d.
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print(f"Valor màxim a d: {d_max}")
print(f"Valor mínim a d: {d_min}")
print(f"Valor mitjà dels valors de : {d_mean}")


Valor màxim a d: 10
Valor mínim a d: 1
Valor mitjà dels valors de : 4.8


In [51]:
#15. Ahora queremos etiquetar los valores en d. Primero crea un array vacío "f" con la misma forma (es decir, 2x3x5) que d usando `np.empty`.

# Crear un array vacío f con la misma forma que d
f = np.empty(d.shape, dtype=int)

print(f"\nArray f (buit) amb la mateixa forma de d:\n{f}")
print(f"\nForma de f: {f.shape}")


Array f (buit) amb la mateixa forma de d:
[[[0 2 1 0 6]
  [0 8 6 3 4]
  [1 6 8 7 0]]

 [[5 7 4 5 1]
  [0 7 4 0 3]
  [3 2 4 8 9]]]

Forma de f: (2, 3, 5)


In [53]:
#16. Rellena los valores en f. Para cada valor en d, si es mayor que d_min pero menor que d_mean, asigna 25 al valor correspondiente en f.
# Si un valor en d es mayor que d_mean pero menor que d_max, asigna 75 al valor correspondiente en f.
# Si un valor es igual a d_mean, asigna 50 al valor correspondiente en f.

# Asigna 0 al valor correspondiente(s) en f para d_min en d.
# Asigna 100 al valor correspondiente(s) en f para d_max en d.
# Al final, f debería tener solo los siguientes valores: 0, 25, 50, 75 y 100.
# Nota: no necesitas usar Numpy en esta pregunta.

# Omplim l'arrai f segons les condicions:
for i in range(d.shape[0]):  # iterem sobre la primera dimensió (X, , )
    for j in range(d.shape[1]):  # iterem sobre la segona dimensió ( ,Y, )
        for k in range(d.shape[2]):  # iterem sobre la tercera dimensió ( , ,Z)
            if d[i, j, k] == d_min:
                f[i, j, k] = 0
            elif d[i, j, k] == d_mean:
                f[i, j, k] = 50
            elif d[i, j, k] == d_max:
                f[i, j, k] = 100
            elif d_min < d[i, j, k] < d_mean:
                f[i, j, k] = 25
            elif d_mean < d[i, j, k] < d_max:
                f[i, j, k] = 75

print(f"Array f aplicant les condicions:\n{f}")


Array f aplicant les condicions:
[[[  0  25  25   0  75]
  [  0  75  75  25  75]
  [ 25  75  75  75   0]]

 [[ 75  75  75  75  25]
  [  0  75  75   0  25]
  [ 25  25  75  75 100]]]


In [55]:
#17. Imprime d y f. ¿Tienes el f esperado?

print(f"\nL'array d és:\n {d}")
print(f"\nL'array f és:\n {f}")
print(f"\nEl valor mitjà de d és: {d_mean}. Com que és un nombre decimal i els valors de f són tots naturals no tenim cap valor 50 a l'array f")


L'array d és:
 [[[ 1  3  2  1  7]
  [ 1  9  7  4  5]
  [ 2  7  9  8  1]]

 [[ 6  8  5  6  2]
  [ 1  8  5  1  4]
  [ 4  3  5  9 10]]]

L'array f és:
 [[[  0  25  25   0  75]
  [  0  75  75  25  75]
  [ 25  75  75  75   0]]

 [[ 75  75  75  75  25]
  [  0  75  75   0  25]
  [ 25  25  75  75 100]]]

El valor mitjà de d és: 4.8. Com que és un nombre decimal i els valors de f són tots naturals no tenim cap valor 50 a l'array f


In [63]:
#18. Pregunta de bonificación: en lugar de usar números (es decir, 0, 25, 50, 75 y 100), ¿cómo usar valores de cadena 
# ("A", "B", "C", "D" y "E") para etiquetar los elementos del array? Esperas el resultado sea:
# array([[[ 'D',  'D',  'D',  'B',  'D'],
#       [ 'D',  'D',  'B',  'B',  'B'],
#       [ 'D',  'B',  'D',  'D',  'D']],
#
#      [[ 'B',  'B',  'B',  'B',  'E'],
#       [ 'D',  'D',  'D',  'D',  'D'],
#       [ 'B',  'D',   'A',  'D', 'D']]])
# De nuevo, no necesitas Numpy en esta pregunta.

# Com que he definit f amb valors senzers, caldrà redefinir f o definir una nova funció g amb les mateixes característiques.

g = np.empty(d.shape, dtype=str)

for i in range(d.shape[0]):  
    for j in range(d.shape[1]):  
        for k in range(d.shape[2]): 
            if d[i, j, k] == d_min:
                g[i, j, k] = "A"  
            elif d[i, j, k] == d_mean:
                g[i, j, k] = "C"  
            elif d[i, j, k] == d_max:
                g[i, j, k] = "E"  
            elif d_min < d[i, j, k] < d_mean:
                g[i, j, k] = "B" 
            elif d_mean < d[i, j, k] < d_max:
                g[i, j, k] = "D"  

print(f"Array g:\n{g}")

Array g:
[[['A' 'B' 'B' 'A' 'D']
  ['A' 'D' 'D' 'B' 'D']
  ['B' 'D' 'D' 'D' 'A']]

 [['D' 'D' 'D' 'D' 'B']
  ['A' 'D' 'D' 'A' 'B']
  ['B' 'B' 'D' 'D' 'E']]]
