In [86]:
#1. Importa el paquete NUMPY bajo el nombre np.
import numpy as np

In [87]:
#2. Imprime la versión de NUMPY y la configuración.
print(np.__version__)
np.show_config()

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep139863411681952
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -fno-strict-aliasing
    commands: cc
    linker: ld.bfd
    linker args: -Wl,--strip-debug, -fno-strict-aliasing
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    linker args: -Wl,--strip-debug
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
   

In [88]:
#3. Genera un array tridimensional de 2x3x5 con valores aleatorios. Asigna el array a la variable "a"
# Desafío: hay al menos tres maneras fáciles que usan numpy para generar arrays aleatorios. ¿Cuántas formas puedes encontrar?

# Forma 1: Números enteros aleatorios en el intervalo [0, 10).
a1 = np.random.randint(10,size=(2, 3, 5))

# Forma 2: Números decimales aleatorios en el intervalo [0.0, 1.0).
a2 = np.random.random((2, 3, 5))

# Forma 3: Números aleatorios de una distribución uniforme en el intervalo [0.0, 1.0)
a3 = np.random.uniform(low=0.0, high=1.0, size=(2, 3, 5))

# Forma 4: Números aleatorios estándar con distribución normal con media 0 y desviación 1.
a4 = np.random.randn(2, 3, 5)

# Forma 5: Números aleatorios de una distribución normal con media "loc" y desviación estándar "scale".
a5 = np.random.normal(loc=0.0, scale=1.0, size=(2, 3, 5))

# Forma 6: Elegir aleatoriamente elementos de una lista específica (puede aceptar parámetros adicionales como replace=False para la selección sin reemplazo.)
a6 = np.random.choice(range(10), size=(2, 3, 5))

In [89]:
#4. Imprime a.
# Seleción la generación aleatoria deseada
a = a1 #a1, a2, a3, a4, a5, a6
# Impresión de a
print (a)

[[[5 0 7 3 0]
  [2 6 9 2 4]
  [2 0 2 8 8]]

 [[5 7 3 4 7]
  [7 9 3 5 3]
  [7 8 5 9 4]]]


In [90]:
#5. Crea un array tridimensional de 5x2x3 con todos los valores igual a 1.
#Asigna el array a la variable "b"
b = np.ones((5, 2, 3))

In [91]:
#6. Imprime b.
print (b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [92]:
#7. ¿Tienen a y b el mismo tamaño? ¿Cómo lo demuestras en código Python?
def numpy_info(arr):
  print("\nThe dimension is:", arr.ndim)
  print("The shape is:", arr.shape)
  print("The size is:", arr.size)

numpy_info(a)
numpy_info(b)

print("\nTienen la misma dimensión? ", a.ndim == b.ndim)
print("Tienen la misma forma? ", a.shape == b.shape)
print("Tienen el mismo tamaño? ", a.size == b.size)


The dimension is: 3
The shape is: (2, 3, 5)
The size is: 30

The dimension is: 3
The shape is: (5, 2, 3)
The size is: 30

Tienen la misma dimensión?  True
Tienen la misma forma?  False
Tienen el mismo tamaño?  True


**Dimension** (*arr.ndim*): This method returns the number of dimensions in the input array arr. For example, if arr is a 1-dimensional array, it will return 1 (vector). If it's a 2-dimensional array, it will return 2 (matrix), and so on.

**Shape** (*arr.shape*): This method returns a tuple representing the dimensions of the array. The tuple contains the length of the array along each dimension. For example, if arr is a 1-dimensional array with 7 elements, it will return (7,). If it's a 2-dimensional array with dimensions 3x4, it will return (3, 4).

**Size** (*arr.size*): This method returns the total number of elements in the array. It's essentially the product of the lengths of all dimensions. For example, if arr is a 2-dimensional array with dimensions 3x4, it will return 12 because there are a total of 12 elements in the array.

Fuente: Teoría IronHack

In [93]:
#8. ¿Es posible sumar a y b? ¿Por qué sí o por qué no?
print("No se podrán sumar a y b porque tienen tamaños (Shape) diferentes")
print("a tiene forma (shape): ", a.shape)
print("b tiene forma (shape): ", b.shape)

No se podrán sumar a y b porque tienen tamaños (Shape) diferentes
a tiene forma (shape):  (2, 3, 5)
b tiene forma (shape):  (5, 2, 3)


In [94]:
try:
  # Prueba de sumar a + b y si se puede devolver mensaje exitoso y el resultado
    result = a + b
    print(f"La suma fue exitosa. El resultado es: {result}")
except ValueError as e:
  # Si no se puede sumar, devolver mensaje de error con el error
    print(f"Error: No se pueden sumar los arrays debido a incompatibilidad de dimensiones. Detalles: {e}")

Error: No se pueden sumar los arrays debido a incompatibilidad de dimensiones. Detalles: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 


In [95]:
#9. Transpone b para que tenga la misma estructura que a (es decir, se convierta en un array de 2x3x5). Asigna el array transpuesto a la variable "c".

# Se transpone b para que el shape[0] vaya en la ultima posición, el shape[1] en la primera, el shape [2] en la segunda posición
# O sea para pasar de (5, 2, 3) a (2, 3, 5)
 #                    [0][1][2]   [1][2][0]
c = np.transpose(b, axes=(1, 2, 0))

In [96]:
numpy_info(a)
numpy_info(c)

print("\nTienen la misma dimensión? ", a.ndim == c.ndim)
print("Tienen la misma forma? ", a.shape == c.shape)
print("Tienen el mismo tamaño? ", a.size == c.size)

# Pero b transpuesta (c) no tiene la misma estructura que a (no es un array de tamaño 2x3x5)


The dimension is: 3
The shape is: (2, 3, 5)
The size is: 30

The dimension is: 3
The shape is: (2, 3, 5)
The size is: 30

Tienen la misma dimensión?  True
Tienen la misma forma?  True
Tienen el mismo tamaño?  True


In [97]:
#10. Intenta sumar a y c. Ahora debería funcionar. Asigna la suma a la variable "d". Pero, ¿por qué funciona ahora?
try:
  # Prueba de sumar a + b y si se puede devolver mensaje exitoso y el resultado
    d = a + c
    print(f"La suma fue exitosa. El resultado es: {d}")
except ValueError as e:
  # Si no se puede sumar, devolver mensaje de error con el error
    print(f"Error: No se pueden sumar los arrays debido a incompatibilidad de dimensiones. Detalles: {e}")

La suma fue exitosa. El resultado es: [[[ 6.  1.  8.  4.  1.]
  [ 3.  7. 10.  3.  5.]
  [ 3.  1.  3.  9.  9.]]

 [[ 6.  8.  4.  5.  8.]
  [ 8. 10.  4.  6.  4.]
  [ 8.  9.  6. 10.  5.]]]


In [98]:
#11. Imprime a y d. ¿Notas la diferencia y la relación entre los dos arrays en términos de los valores? Explica.
print(a)
print(d)

[[[5 0 7 3 0]
  [2 6 9 2 4]
  [2 0 2 8 8]]

 [[5 7 3 4 7]
  [7 9 3 5 3]
  [7 8 5 9 4]]]
[[[ 6.  1.  8.  4.  1.]
  [ 3.  7. 10.  3.  5.]
  [ 3.  1.  3.  9.  9.]]

 [[ 6.  8.  4.  5.  8.]
  [ 8. 10.  4.  6.  4.]
  [ 8.  9.  6. 10.  5.]]]


In [99]:
# Notamos que "a" son enteros y "d" son float.
print(f"El tipo de datos de a es {type(a[0,0,0])}\nEl tipo de datos de d es {type(d[0,0,0])}")

# Eso es debido que
# "a" es generado con enteros aleatorios.
# "d" es una suma entre float de unos "b" y enteros "a" que da como resultado un float

print(f"Respecto a los números se observa que todos diferencian en una unidad del otro")
print(d-a)

# Eso es debido a que acabamos de sumar unos en todas las posiciones (hemos sumado b)

El tipo de datos de a es <class 'numpy.int64'>
El tipo de datos de d es <class 'numpy.float64'>
Respecto a los números se observa que todos diferencian en una unidad del otro
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [100]:
#12. Multiplica a y c. Asigna el resultado a e.
e = a*c

In [101]:
#13. ¿Es e igual a a? ¿Por qué sí o por qué no?
e == a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [102]:
print("Sí, e es igual a a por qué se han multiplicado todos los elementos de a por 1")

Sí, e es igual a a por qué se han multiplicado todos los elementos de a por 1


In [103]:
#14. Identifica los valores máximos, mínimos y medios en d. Asigna esos valores a las variables "d_max", "d_min" y "d_mean"
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print("Máximo = ", d_max)
print("Mínimo = ", d_min)
print("Media = ", d_mean)

Máximo =  10.0
Mínimo =  1.0
Media =  5.8


In [104]:
#15. Ahora queremos etiquetar los valores en d. Primero crea un array vacío "f" con la misma forma (es decir, 2x3x5) que d usando `np.empty`.
f = np.empty([2,3,5])
f

array([[[7., 8., 6., 5., 0.],
        [8., 6., 7., 2., 3.],
        [3., 3., 0., 1., 1.]],

       [[4., 4., 1., 9., 9.],
        [3., 5., 0., 9., 1.],
        [6., 6., 5., 3., 2.]]])

In [118]:
"""
#16. Rellena los valores en f. Para cada valor en d, si es mayor que d_min pero menor que d_mean, asigna 25 al valor correspondiente en f.
Si un valor en d es mayor que d_mean pero menor que d_max, asigna 75 al valor correspondiente en f.
Si un valor es igual a d_mean, asigna 50 al valor correspondiente en f.
Asigna 0 al valor correspondiente(s) en f para d_min en d.
Asigna 100 al valor correspondiente(s) en f para d_max en d.
Al final, f debería tener solo los siguientes valores: 0, 25, 50, 75 y 100.
Nota: no necesitas usar Numpy en esta pregunta.
"""

## FORMA 1: ITERANDO SOBRE LOS ELEMENTOS
# Se iteran las dos matrices.
for m, matrix in enumerate(d):
  # Se iteran las tres filas.
  for r, row in enumerate(matrix):
   # Se iteran los cinco elementos de cada fila (las columnas).
    for c, element in enumerate(row):
        if d_min < element < d_mean:
            f[m,r,c] = 25
        elif d_mean < element < d_max:
            f[m,r,c] = 75
        elif element == d_mean:
            f[m,r,c] = 50
        elif element == d_min:
            f[m,r,c] = 0
        else: #element == d_max
            f[m,r,c] = 100

## FORMA 2: ASIGNANDO CON MÁSCARAS SOBRE LOS ELEMENTOS
f[(d > d_min) & (d < d_mean)] = 25
f[(d > d_mean) & (d < d_max)] = 75
f[d == d_mean] = 50
f[d == d_min] = 0
f[d == d_max] = 100

In [117]:
#17. Imprime d y f. ¿Tienes el f esperado?
"""Por ejemplo, si tu d es:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Tu f debería ser:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])"""
print("Máximo = ", d_max)
print("Mínimo = ", d_min)
print("Media = ", d_mean)
print(d)
print(f)
# El resultado es el esperado

Máximo =  10.0
Mínimo =  1.0
Media =  5.8
[[[ 6.  1.  8.  4.  1.]
  [ 3.  7. 10.  3.  5.]
  [ 3.  1.  3.  9.  9.]]

 [[ 6.  8.  4.  5.  8.]
  [ 8. 10.  4.  6.  4.]
  [ 8.  9.  6. 10.  5.]]]
[[[ 75.   0.  75.  25.   0.]
  [ 25.  75. 100.  25.  25.]
  [ 25.   0.  25.  75.  75.]]

 [[ 75.  75.  25.  25.  75.]
  [ 75. 100.  25.  75.  25.]
  [ 75.  75.  75. 100.  25.]]]


In [115]:
"""
#18. Pregunta de bonificación: en lugar de usar números (es decir, 0, 25, 50, 75 y 100), ¿cómo usar valores de cadena
("A", "B", "C", "D" y "E") para etiquetar los elementos del array? Esperas el resultado sea:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
De nuevo, no necesitas Numpy en esta pregunta.
"""

""" Criterios de Conversión
0 → "A"
25 → "B"
50 → "C"
75 → "D"
100 → "E" """

g = np.empty_like(f, dtype=str)  # Crear un array de cadenas con el mismo tamaño
g[f == 0] = 'A'
g[f == 25] = 'B'
g[f == 50] = 'C'
g[f == 75] = 'D'
g[f == 100] = 'E'

print(g)

[[['D' 'A' 'D' 'B' 'A']
  ['B' 'D' 'E' 'B' 'B']
  ['B' 'A' 'B' 'D' 'D']]

 [['D' 'D' 'B' 'B' 'D']
  ['D' 'E' 'B' 'D' 'B']
  ['D' 'D' 'D' 'E' 'B']]]
